language: java
jdk: openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone https://github.com/suloginscene/common.git ../common
  - cd ../common
  - mvn install
  - cd ../member-server

notifications:
  email:
    recipients:
      - suloginscene@gmail.com
