language: java
jdk: openjdk11

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone https://github.com/suloginscene/jjwt-helper.git ../jjwt-helper
  - cd ../jjwt-helper
  - mvn install
  - git clone https://github.com/suloginscene/jwt-config.git ../jwt-config
  - cd ../jwt-config
  - mvn install
  - cd ../auth-server

notifications:
  email:
    recipients:
      - suloginscene@gmail.com
